class BraceletExecutor{
public static void main(String[] args){

Bracelet b1=new Bracelet();
b1.brand="Tanishq";
b1.colour="Gold";
b1.material="Gold";
b1.price=25000;
b1.weight=15.5;
b1.type="Chain";
b1.size="Medium";
b1.design="Floral";
b1.gender="Women";
b1.originCountry="India";
b1.stoneType="Diamond";
b1.adjustable=true;
b1.warrantyYears=2;
b1.finish="Glossy";
b1.length=18.5;
b1.width=1.2;
b1.closureType="Hook";
b1.occasion="Wedding";
b1.style="Traditional";
b1.rating=5;

System.out.println(b1.brand);
System.out.println(b1.colour);
System.out.println(b1.material);
System.out.println(b1.price);
System.out.println(b1.weight);
System.out.println(b1.type);
System.out.println(b1.size);
System.out.println(b1.design);
System.out.println(b1.gender);
System.out.println(b1.originCountry);
System.out.println(b1.stoneType);
System.out.println(b1.adjustable);
System.out.println(b1.warrantyYears);
System.out.println(b1.finish);
System.out.println(b1.length);
System.out.println(b1.width);
System.out.println(b1.closureType);
System.out.println(b1.occasion);
System.out.println(b1.style);
System.out.println(b1.rating);


Bracelet b2=new Bracelet();
b2.brand="Malabar";
b2.colour="Silver";
b2.material="Silver";
b2.price=8000;
b2.weight=10.2;
b2.type="Bangle";
b2.size="Small";
b2.design="Leaf";
b2.gender="Women";
b2.originCountry="India";
b2.stoneType="Ruby";
b2.adjustable=true;
b2.warrantyYears=1;
b2.finish="Matte";
b2.length=17.5;
b2.width=1.0;
b2.closureType="Clip";
b2.occasion="Party";
b2.style="Modern";
b2.rating=4;

System.out.println(b2.brand);
System.out.println(b2.colour);
System.out.println(b2.material);
System.out.println(b2.price);
System.out.println(b2.weight);
System.out.println(b2.type);
System.out.println(b2.size);
System.out.println(b2.design);
System.out.println(b2.gender);
System.out.println(b2.originCountry);
System.out.println(b2.stoneType);
System.out.println(b2.adjustable);
System.out.println(b2.warrantyYears);
System.out.println(b2.finish);
System.out.println(b2.length);
System.out.println(b2.width);
System.out.println(b2.closureType);
System.out.println(b2.occasion);
System.out.println(b2.style);
System.out.println(b2.rating);


Bracelet b3=new Bracelet();
b3.brand="Kalyan";
b3.colour="RoseGold";
b3.material="Gold";
b3.price=22000;
b3.weight=12.5;
b3.type="Chain";
b3.size="Large";
b3.design="Heart";
b3.gender="Women";
b3.originCountry="India";
b3.stoneType="Emerald";
b3.adjustable=false;
b3.warrantyYears=3;
b3.finish="Glossy";
b3.length=19.0;
b3.width=1.3;
b3.closureType="Hook";
b3.occasion="Festival";
b3.style="Traditional";
b3.rating=5;

System.out.println(b3.brand);
System.out.println(b3.colour);
System.out.println(b3.material);
System.out.println(b3.price);
System.out.println(b3.weight);
System.out.println(b3.type);
System.out.println(b3.size);
System.out.println(b3.design);
System.out.println(b3.gender);
System.out.println(b3.originCountry);
System.out.println(b3.stoneType);
System.out.println(b3.adjustable);
System.out.println(b3.warrantyYears);
System.out.println(b3.finish);
System.out.println(b3.length);
System.out.println(b3.width);
System.out.println(b3.closureType);
System.out.println(b3.occasion);
System.out.println(b3.style);
System.out.println(b3.rating);


Bracelet p1=new Bracelet("Tanishq","Gold","Gold",25000,15.5,"Chain","Medium","Floral","Women","India","Diamond",true,2,"Glossy",18.5,1.2,"Hook","Wedding","Traditional",5);
System.out.println(p1.brand);
System.out.println(p1.colour);
System.out.println(p1.material);
System.out.println(p1.price);
System.out.println(p1.weight);
System.out.println(p1.type);
System.out.println(p1.size);
System.out.println(p1.design);
System.out.println(p1.gender);
System.out.println(p1.originCountry);
System.out.println(p1.stoneType);
System.out.println(p1.adjustable);
System.out.println(p1.warrantyYears);
System.out.println(p1.finish);
System.out.println(p1.length);
System.out.println(p1.width);
System.out.println(p1.closureType);
System.out.println(p1.occasion);
System.out.println(p1.style);
System.out.println(p1.rating);


Bracelet p2=new Bracelet("Malabar","Silver","Silver",8000,10.2,"Bangle","Small","Leaf","Women","India","Ruby",true,1,"Matte",17.5,1.0,"Clip","Party","Modern",4);
System.out.println(p2.brand);
System.out.println(p2.colour);
System.out.println(p2.material);
System.out.println(p2.price);
System.out.println(p2.weight);
System.out.println(p2.type);
System.out.println(p2.size);
System.out.println(p2.design);
System.out.println(p2.gender);
System.out.println(p2.originCountry);
System.out.println(p2.stoneType);
System.out.println(p2.adjustable);
System.out.println(p2.warrantyYears);
System.out.println(p2.finish);
System.out.println(p2.length);
System.out.println(p2.width);
System.out.println(p2.closureType);
System.out.println(p2.occasion);
System.out.println(p2.style);
System.out.println(p2.rating);


Bracelet p3=new Bracelet("Kalyan","RoseGold","Gold",22000,12.5,"Chain","Large","Heart","Women","India","Emerald",false,3,"Glossy",19.0,1.3,"Hook","Festival","Traditional",5);
System.out.println(p3.brand);
System.out.println(p3.colour);
System.out.println(p3.material);
System.out.println(p3.price);
System.out.println(p3.weight);
System.out.println(p3.type);
System.out.println(p3.size);
System.out.println(p3.design);
System.out.println(p3.gender);
System.out.println(p3.originCountry);
System.out.println(p3.stoneType);
System.out.println(p3.adjustable);
System.out.println(p3.warrantyYears);
System.out.println(p3.finish);
System.out.println(p3.length);
System.out.println(p3.width);
System.out.println(p3.closureType);
System.out.println(p3.occasion);
System.out.println(p3.style);
System.out.println(p3.rating);

}
}