class CameraExecutor {
    public static void main(String[] details) {

        boolean cameraCreated;

        cameraCreated = Camera.createCamera("f/2.8","1/1000s","+0.3","RAW","Daylight","200mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/4","1/500s","+0.0","JPEG","Auto","85mm","Continuous","BurstHigh","CenterWeighted");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/1.8","1/2000s","+0.7","RAW","Daylight","135mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/5.6","1/250s","-0.3","JPEG","Cloudy","50mm","Single","SingleShot","Spot");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/3.5","1/800s","+0.3","RAW","Auto","70mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/2.0","1/1600s","+0.5","RAW","Daylight","200mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/8","1/125s","0.0","JPEG","Sunny","24mm","Single","SingleShot","Matrix");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/4.5","1/640s","+0.3","RAW","Auto","100mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/2.2","1/1200s","+0.4","RAW","Daylight","150mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/6.3","1/320s","-0.3","JPEG","Cloudy","35mm","Single","SingleShot","CenterWeighted");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/2.8","1/1000s","+0.2","RAW","Auto","200mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/4","1/500s","+0.1","JPEG","Daylight","90mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/1.8","1/2000s","+0.6","RAW","Sunny","135mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/5.6","1/250s","-0.2","JPEG","Auto","55mm","Single","SingleShot","Spot");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/3.5","1/800s","+0.3","RAW","Daylight","70mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/2.0","1/1600s","+0.5","RAW","Auto","210mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/7.1","1/200s","0.0","JPEG","Cloudy","28mm","Single","SingleShot","Matrix");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/4.5","1/640s","+0.2","RAW","Daylight","105mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/2.2","1/1250s","+0.4","RAW","Auto","160mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/6.3","1/320s","-0.4","JPEG","Sunny","40mm","Single","SingleShot","CenterWeighted");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/2.8","1/900s","+0.3","RAW","Daylight","180mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/4","1/450s","+0.1","JPEG","Auto","95mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/1.8","1/2100s","+0.6","RAW","Daylight","140mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/5.6","1/260s","-0.2","JPEG","Cloudy","60mm","Single","SingleShot","Spot");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/3.5","1/820s","+0.3","RAW","Auto","75mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/2.0","1/1700s","+0.5","RAW","Daylight","220mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/8","1/130s","0.0","JPEG","Sunny","26mm","Single","SingleShot","Matrix");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/4.5","1/660s","+0.2","RAW","Auto","110mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/2.2","1/1180s","+0.4","RAW","Daylight","170mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/6.3","1/340s","-0.4","JPEG","Cloudy","42mm","Single","SingleShot","CenterWeighted");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/2.8","1/950s","+0.3","RAW","Auto","190mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/4","1/480s","+0.1","JPEG","Daylight","88mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/1.8","1/2050s","+0.6","RAW","Sunny","145mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/5.6","1/255s","-0.2","JPEG","Auto","58mm","Single","SingleShot","Spot");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/3.5","1/810s","+0.3","RAW","Daylight","72mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/2.0","1/1650s","+0.5","RAW","Auto","230mm","Continuous","BurstHigh","Evaluative");
		        Camera.getCamera();
        cameraCreated = Camera.createCamera("f/7.1","1/210s","0.0","JPEG","Cloudy","30mm","Single","SingleShot","Matrix");

        Camera.getCamera();
    }
}