class NecklaceExecutor{
public static void main(String[] args){

Necklace n1=new Necklace();
n1.brand="Tanishq";
n1.colour="Gold";
n1.material="Gold";
n1.price=50000;
n1.weight=25.5;
n1.type="Chain";
n1.size="Medium";
n1.design="Floral";
n1.gender="Women";
n1.originCountry="India";
n1.stoneType="Diamond";
n1.adjustable=true;
n1.warrantyYears=2;
n1.finish="Glossy";
n1.length=22.5;
n1.width=1.5;
n1.closureType="Hook";
n1.occasion="Wedding";
n1.style="Traditional";
n1.rating=5;

System.out.println(n1.brand);
System.out.println(n1.colour);
System.out.println(n1.material);
System.out.println(n1.price);
System.out.println(n1.weight);
System.out.println(n1.type);
System.out.println(n1.size);
System.out.println(n1.design);
System.out.println(n1.gender);
System.out.println(n1.originCountry);
System.out.println(n1.stoneType);
System.out.println(n1.adjustable);
System.out.println(n1.warrantyYears);
System.out.println(n1.finish);
System.out.println(n1.length);
System.out.println(n1.width);
System.out.println(n1.closureType);
System.out.println(n1.occasion);
System.out.println(n1.style);
System.out.println(n1.rating);


Necklace n2=new Necklace();
n2.brand="Malabar";
n2.colour="Silver";
n2.material="Silver";
n2.price=20000;
n2.weight=18.2;
n2.type="Beads";
n2.size="Small";
n2.design="Leaf";
n2.gender="Women";
n2.originCountry="India";
n2.stoneType="Ruby";
n2.adjustable=true;
n2.warrantyYears=1;
n2.finish="Matte";
n2.length=20.0;
n2.width=1.2;
n2.closureType="Clip";
n2.occasion="Party";
n2.style="Modern";
n2.rating=4;

System.out.println(n2.brand);
System.out.println(n2.colour);
System.out.println(n2.material);
System.out.println(n2.price);
System.out.println(n2.weight);
System.out.println(n2.type);
System.out.println(n2.size);
System.out.println(n2.design);
System.out.println(n2.gender);
System.out.println(n2.originCountry);
System.out.println(n2.stoneType);
System.out.println(n2.adjustable);
System.out.println(n2.warrantyYears);
System.out.println(n2.finish);
System.out.println(n2.length);
System.out.println(n2.width);
System.out.println(n2.closureType);
System.out.println(n2.occasion);
System.out.println(n2.style);
System.out.println(n2.rating);


Necklace n3=new Necklace();
n3.brand="Kalyan";
n3.colour="RoseGold";
n3.material="Gold";
n3.price=45000;
n3.weight=22.5;
n3.type="Chain";
n3.size="Large";
n3.design="Heart";
n3.gender="Women";
n3.originCountry="India";
n3.stoneType="Emerald";
n3.adjustable=false;
n3.warrantyYears=3;
n3.finish="Glossy";
n3.length=24.0;
n3.width=1.8;
n3.closureType="Hook";
n3.occasion="Festival";
n3.style="Traditional";
n3.rating=5;

System.out.println(n3.brand);
System.out.println(n3.colour);
System.out.println(n3.material);
System.out.println(n3.price);
System.out.println(n3.weight);
System.out.println(n3.type);
System.out.println(n3.size);
System.out.println(n3.design);
System.out.println(n3.gender);
System.out.println(n3.originCountry);
System.out.println(n3.stoneType);
System.out.println(n3.adjustable);
System.out.println(n3.warrantyYears);
System.out.println(n3.finish);
System.out.println(n3.length);
System.out.println(n3.width);
System.out.println(n3.closureType);
System.out.println(n3.occasion);
System.out.println(n3.style);
System.out.println(n3.rating);


Necklace p1=new Necklace("Tanishq","Gold","Gold",50000,25.5,"Chain","Medium","Floral","Women","India","Diamond",true,2,"Glossy",22.5,1.5,"Hook","Wedding","Traditional",5);
System.out.println(p1.brand);
System.out.println(p1.colour);
System.out.println(p1.material);
System.out.println(p1.price);
System.out.println(p1.weight);
System.out.println(p1.type);
System.out.println(p1.size);
System.out.println(p1.design);
System.out.println(p1.gender);
System.out.println(p1.originCountry);
System.out.println(p1.stoneType);
System.out.println(p1.adjustable);
System.out.println(p1.warrantyYears);
System.out.println(p1.finish);
System.out.println(p1.length);
System.out.println(p1.width);
System.out.println(p1.closureType);
System.out.println(p1.occasion);
System.out.println(p1.style);
System.out.println(p1.rating);


Necklace p2=new Necklace("Malabar","Silver","Silver",20000,18.2,"Beads","Small","Leaf","Women","India","Ruby",true,1,"Matte",20.0,1.2,"Clip","Party","Modern",4);
System.out.println(p2.brand);
System.out.println(p2.colour);
System.out.println(p2.material);
System.out.println(p2.price);
System.out.println(p2.weight);
System.out.println(p2.type);
System.out.println(p2.size);
System.out.println(p2.design);
System.out.println(p2.gender);
System.out.println(p2.originCountry);
System.out.println(p2.stoneType);
System.out.println(p2.adjustable);
System.out.println(p2.warrantyYears);
System.out.println(p2.finish);
System.out.println(p2.length);
System.out.println(p2.width);
System.out.println(p2.closureType);
System.out.println(p2.occasion);
System.out.println(p2.style);
System.out.println(p2.rating);


Necklace p3=new Necklace("Kalyan","RoseGold","Gold",45000,22.5,"Chain","Large","Heart","Women","India","Emerald",false,3,"Glossy",24.0,1.8,"Hook","Festival","Traditional",5);
System.out.println(p3.brand);
System.out.println(p3.colour);
System.out.println(p3.material);
System.out.println(p3.price);
System.out.println(p3.weight);
System.out.println(p3.type);
System.out.println(p3.size);
System.out.println(p3.design);
System.out.println(p3.gender);
System.out.println(p3.originCountry);
System.out.println(p3.stoneType);
System.out.println(p3.adjustable);
System.out.println(p3.warrantyYears);
System.out.println(p3.finish);
System.out.println(p3.length);
System.out.println(p3.width);
System.out.println(p3.closureType);
System.out.println(p3.occasion);
System.out.println(p3.style);
System.out.println(p3.rating);

}
}