class RacketExecutor{
public static void main(String[] args){

Racket r1=new Racket();
r1.brand="Yonex";
r1.sport="Badminton";
r1.colour="Black";
r1.material="Carbon";
r1.weight=85;
r1.length=67;
r1.gripType="Rubber";
r1.price=3500;
r1.stringCount=22;
r1.originCountry="Japan";
System.out.println(r1.brand);
System.out.println(r1.sport);
System.out.println(r1.colour);
System.out.println(r1.material);
System.out.println(r1.weight);
System.out.println(r1.length);
System.out.println(r1.gripType);
System.out.println(r1.price);
System.out.println(r1.stringCount);
System.out.println(r1.originCountry);

Racket r2=new Racket();
r2.brand="Wilson";
r2.sport="Tennis";
r2.colour="Red";
r2.material="Graphite";
r2.weight=300;
r2.length=68;
r2.gripType="Foam";
r2.price=5000;
r2.stringCount=16;
r2.originCountry="USA";
System.out.println(r2.brand);
System.out.println(r2.sport);
System.out.println(r2.colour);
System.out.println(r2.material);
System.out.println(r2.weight);
System.out.println(r2.length);
System.out.println(r2.gripType);
System.out.println(r2.price);
System.out.println(r2.stringCount);
System.out.println(r2.originCountry);

Racket r3=new Racket();
r3.brand="Head";
r3.sport="Tennis";
r3.colour="Blue";
r3.material="Graphene";
r3.weight=295;
r3.length=68;
r3.gripType="Rubber";
r3.price=4800;
r3.stringCount=18;
r3.originCountry="Austria";
System.out.println(r3.brand);
System.out.println(r3.sport);
System.out.println(r3.colour);
System.out.println(r3.material);
System.out.println(r3.weight);
System.out.println(r3.length);
System.out.println(r3.gripType);
System.out.println(r3.price);
System.out.println(r3.stringCount);
System.out.println(r3.originCountry);

Racket r4=new Racket();
r4.brand="LiNing";
r4.sport="Badminton";
r4.colour="Green";
r4.material="Carbon";
r4.weight=82;
r4.length=67;
r4.gripType="Rubber";
r4.price=4200;
r4.stringCount=22;
r4.originCountry="China";
System.out.println(r4.brand);
System.out.println(r4.sport);
System.out.println(r4.colour);
System.out.println(r4.material);
System.out.println(r4.weight);
System.out.println(r4.length);
System.out.println(r4.gripType);
System.out.println(r4.price);
System.out.println(r4.stringCount);
System.out.println(r4.originCountry);

Racket r5=new Racket();
r5.brand="Babolat";
r5.sport="Tennis";
r5.colour="Yellow";
r5.material="Graphite";
r5.weight=305;
r5.length=68;
r5.gripType="Foam";
r5.price=5300;
r5.stringCount=16;
r5.originCountry="France";
System.out.println(r5.brand);
System.out.println(r5.sport);
System.out.println(r5.colour);
System.out.println(r5.material);
System.out.println(r5.weight);
System.out.println(r5.length);
System.out.println(r5.gripType);
System.out.println(r5.price);
System.out.println(r5.stringCount);
System.out.println(r5.originCountry);


Racket p1=new Racket("Yonex","Badminton","Black","Carbon",85,67,"Rubber",3500,22,"Japan");
System.out.println(p1.brand);
System.out.println(p1.sport);
System.out.println(p1.colour);
System.out.println(p1.material);
System.out.println(p1.weight);
System.out.println(p1.length);
System.out.println(p1.gripType);
System.out.println(p1.price);
System.out.println(p1.stringCount);
System.out.println(p1.originCountry);

Racket p2=new Racket("Wilson","Tennis","Red","Graphite",300,68,"Foam",5000,16,"USA");
System.out.println(p2.brand);
System.out.println(p2.sport);
System.out.println(p2.colour);
System.out.println(p2.material);
System.out.println(p2.weight);
System.out.println(p2.length);
System.out.println(p2.gripType);
System.out.println(p2.price);
System.out.println(p2.stringCount);
System.out.println(p2.originCountry);

Racket p3=new Racket("Head","Tennis","Blue","Graphene",295,68,"Rubber",4800,18,"Austria");
System.out.println(p3.brand);
System.out.println(p3.sport);
System.out.println(p3.colour);
System.out.println(p3.material);
System.out.println(p3.weight);
System.out.println(p3.length);
System.out.println(p3.gripType);
System.out.println(p3.price);
System.out.println(p3.stringCount);
System.out.println(p3.originCountry);

Racket p4=new Racket("LiNing","Badminton","Green","Carbon",82,67,"Rubber",4200,22,"China");
System.out.println(p4.brand);
System.out.println(p4.sport);
System.out.println(p4.colour);
System.out.println(p4.material);
System.out.println(p4.weight);
System.out.println(p4.length);
System.out.println(p4.gripType);
System.out.println(p4.price);
System.out.println(p4.stringCount);
System.out.println(p4.originCountry);

Racket p5=new Racket("Babolat","Tennis","Yellow","Graphite",305,68,"Foam",5300,16,"France");
System.out.println(p5.brand);
System.out.println(p5.sport);
System.out.println(p5.colour);
System.out.println(p5.material);
System.out.println(p5.weight);
System.out.println(p5.length);
System.out.println(p5.gripType);
System.out.println(p5.price);
System.out.println(p5.stringCount);
System.out.println(p5.originCountry);

}
}